---

- name: 'Finder: Show filename extensions'
  osx_defaults: domain=.GlobalPreferences key=AppleShowAllExtensions type=boolean value=true state=present
  notify: restart finder

- name: 'Finder: New window shows home directory'
  osx_defaults: domain=com.apple.finder key=NewWindowTarget type=string value=PfHm state=present
  notify: restart finder

